---
linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
    disabled-checks:
      - unlambda
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0
  govet:
    enable:
      - fieldalignment
  lll:
    line-length: 140
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    # - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl
issues:
  exclude-rules:
    # Separating explicit var declarations by blank lines seems excessive.
    - linters:
        - wsl
      text: "declarations should never be cuddled"

    # This rule incorrectly flags code where two logically-related lines are
    # followed by an if conditional to check their err return.
    - linters:
        - wsl
      text: "only one cuddle assignment allowed before if statement"

    # Allow dot-imports for Gomega BDD directives per idiomatic Gomega
    - linters:
        - stylecheck
        - golint
      text: "should not use dot imports"
      source: ". \"github.com/onsi/gomega\""

    # Allow dot-imports for Ginkgo BDD directives per idiomatic Ginkgo
    - linters:
        - stylecheck
        - golint
      text: "should not use dot imports"
      source: ". \"github.com/onsi/ginkgo\""

    # Ignore pointer bytes in struct alignment tests (this is a very
    # minor optimisation)
    - linters:
        - govet
      text: "pointer bytes could be"
