ARG BASE_BRANCH
FROM quay.io/submariner/shipyard-dapper-base:release-0.9

ENV DAPPER_ENV="MAKEFLAGS REPO TAG" \
    DAPPER_SOURCE=/go/src/github.com/submariner-io/admiral DAPPER_DOCKER_SOCKET=true
ENV DAPPER_OUTPUT=${DAPPER_SOURCE}/output

WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["/opt/shipyard/scripts/entry"]
CMD ["ci"]
