FROM quay.io/submariner/shipyard-dapper-base:0.4.0

ENV DAPPER_ENV=REPO DAPPER_ENV=TAG \
    DAPPER_SOURCE=/go/src/github.com/submariner-io/admiral DAPPER_DOCKER_SOCKET=true
ENV DAPPER_OUTPUT=${DAPPER_SOURCE}/output

WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
