#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..
mkdir -p bin
echo Building submariner-orchestrator version $VERSION
CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION" -o bin/submariner-orchestrator ./pkg/orchestrator/main.go

