#!/usr/bin/env bash

source ${SCRIPTS_DIR}/lib/debug_functions
source ${SCRIPTS_DIR}/lib/utils

function export_broker_env {
    export BROKER_K8S_REMOTENAMESPACE=broker

    export BROKER_K8S_APISERVER=$(kubectl  -n default get endpoints kubernetes -o jsonpath="{.subsets[0].addresses[0].ip}:{.subsets[0].ports[?(@.name=='https')].port}")

    export BROKER_K8S_CA=$(kubectl -n ${BROKER_K8S_REMOTENAMESPACE} get secrets -o jsonpath="{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='${BROKER_K8S_REMOTENAMESPACE}-client')].data['ca\.crt']}")

    export BROKER_K8S_APISERVERTOKEN=$(kubectl -n ${BROKER_K8S_REMOTENAMESPACE} get secrets -o jsonpath="{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='${BROKER_K8S_REMOTENAMESPACE}-client')].data.token}"|base64 --decode)
}

settings=${DAPPER_SOURCE}/.shipyard.e2e.yml
load_settings
declare_kubeconfig
with_context "${clusters[1]}" export_broker_env

${SCRIPTS_DIR}/e2e.sh "$@"
