---
name: Branch Checks

on:
  pull_request:

permissions: {}

jobs:
  target_branch:
    name: PR targets branch
    runs-on: ubuntu-latest
    steps:
      - name: Check that the PR targets release-0.17
        if: ${{ github.base_ref != 'release-0.17' }}
        run: exit 1
