---
name: Periodic

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  markdown-link-check-periodic:
    name: Markdown Links (all files)
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".markdownlinkcheck.json"

      - name: Raise an Issue to report broken links
        if: ${{ failure() }}
        uses: peter-evans/create-issue-from-file@a04ce672e3acedb1f8e416b46716ddfd09905326
        with:
          title: Broken link detected by periodic linting
          content-filepath: .github/ISSUE_TEMPLATE/broken-link.md
          labels: automated, broken link
