---
name: Reporting

on:
  push:
    branches:
      - devel
      - release-*

permissions: {}

jobs:
  unit-coverage:
    name: Go Unit Test Coverage
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Run Go unit tests
        run: make unit

      - name: Run SonarScan, upload Go test results and coverage
        uses: SonarSource/sonarqube-scan-action@59db25f34e16620e48ab4bb9e4a5dce155cb5432
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
